language: sh

before_script:
  - wget "http://es.archive.ubuntu.com/ubuntu/pool/universe/s/shellcheck/shellcheck_0.3.7-5_amd64.deb"
  - sudo dpkg -i "shellcheck_0.3.7-5_amd64.deb"

script:
  - shellcheck mac

notifications:
  email: false

branches:
  only:
    - master
